version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    platform: linux/amd64
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./db:/var/lib/mysql
